/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// VERSION: 1.0.0-JS

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
})

const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
})

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
})

const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => rootRouteImport,
})

const PatientBookRoute = PatientBookRouteImport.update({
  id: '/patient/book',
  path: '/patient/book',
  getParentRoute: () => rootRouteImport,
})

const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
})

const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
